# Generated by Django 5.2.15 on 2026-07-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="custom_approval_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="custom_brief",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="custom_checklist",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="order",
            name="custom_status",
            field=models.CharField(
                choices=[
                    ("none", "Tidak Ada"),
                    ("requested", "Diminta"),
                    ("scoping", "Briefing"),
                    ("approved", "Disetujui"),
                    ("in_progress", "Dikerjakan"),
                    ("ready", "Siap Review"),
                    ("rejected", "Ditolak"),
                ],
                db_index=True,
                default="none",
                max_length=24,
            ),
        ),
    ]
