from django.urls import path

from orders.views import (
    BillingLifecycleRefreshView,
    StaffArchiveWeddingView,
    StaffClientLifecycleListView,
    StaffConfirmOrderView,
    StaffDashboardMetricsView,
    StaffOrderDetailView,
    StaffOrderListCreateView,
    StaffOrderRevisionDetailView,
    StaffOrderRevisionListCreateView,
    StaffRejectOrderView,
    StaffVerificationQueueView,
)

urlpatterns = [
    path(
        "admin/dashboard/metrics",
        StaffDashboardMetricsView.as_view(),
        name="admin-dashboard-metrics",
    ),
    path("admin/orders", StaffOrderListCreateView.as_view(), name="admin-order-list"),
    path(
        "admin/orders/verification-queue",
        StaffVerificationQueueView.as_view(),
        name="admin-order-verification-queue",
    ),
    path(
        "admin/orders/<slug:reference>/confirm",
        StaffConfirmOrderView.as_view(),
        name="admin-order-confirm",
    ),
    path(
        "admin/orders/<slug:reference>/reject",
        StaffRejectOrderView.as_view(),
        name="admin-order-reject",
    ),
    path(
        "admin/orders/<slug:reference>",
        StaffOrderDetailView.as_view(),
        name="admin-order-detail",
    ),
    path(
        "admin/orders/<slug:reference>/revisions",
        StaffOrderRevisionListCreateView.as_view(),
        name="admin-order-revisions",
    ),
    path(
        "admin/orders/<slug:reference>/revisions/<uuid:revision_id>",
        StaffOrderRevisionDetailView.as_view(),
        name="admin-order-revision-detail",
    ),
    path(
        "admin/client-lifecycle",
        StaffClientLifecycleListView.as_view(),
        name="admin-client-lifecycle",
    ),
    path(
        "admin/weddings/<slug:public_slug>/archive",
        StaffArchiveWeddingView.as_view(),
        name="admin-wedding-archive",
    ),
    path(
        "billing/lifecycle/refresh",
        BillingLifecycleRefreshView.as_view(),
        name="billing-lifecycle-refresh",
    ),
]
