# Generated by Django 5.2.15 on 2026-06-20 17:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=100, unique=True)),
                ("public_value", models.JSONField(blank=True, default=dict)),
                ("private_value", models.JSONField(blank=True, default=dict)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
    ]
