# Generated by Django 5.2.15 on 2026-06-21 01:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherFetchLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("adm4", models.CharField(db_index=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failure", "Failure")], max_length=16
                    ),
                ),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("failure_category", models.CharField(blank=True, max_length=80)),
                ("analysis_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["adm4", "status", "created_at"], name="weather_wea_adm4_f2f815_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeatherSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("adm4", models.CharField(db_index=True, max_length=20)),
                ("analysis_at", models.DateTimeField()),
                ("location", models.JSONField(default=dict)),
                ("forecast", models.JSONField(default=list)),
                ("raw_checksum", models.CharField(max_length=64)),
                ("fetched_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "ordering": ["-analysis_at", "-fetched_at"],
                "indexes": [
                    models.Index(fields=["adm4", "expires_at"], name="weather_wea_adm4_982fd5_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("adm4", "analysis_at"), name="unique_weather_adm4_analysis"
                    )
                ],
            },
        ),
    ]
