# Generated by Django 5.2.15 on 2026-06-20 17:22

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("public_id", models.CharField(max_length=255, unique=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video"), ("raw", "Raw")],
                        default="image",
                        max_length=16,
                    ),
                ),
                ("format", models.CharField(blank=True, max_length=16)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "bytes",
                    models.PositiveBigIntegerField(
                        default=0, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("checksum", models.CharField(blank=True, max_length=128)),
                ("secure_url", models.URLField(max_length=500)),
                ("folder", models.CharField(db_index=True, max_length=120)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["resource_type", "archived_at"],
                        name="media_libra_resourc_2ca91a_idx",
                    )
                ],
            },
        ),
    ]
