# Generated by Django 5.2.15 on 2026-06-20 17:22

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media_library", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.SlugField(max_length=40, unique=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="IDR", max_length=3)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "price"],
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "renderer_key",
                    models.CharField(
                        max_length=80, validators=[common.validators.validate_renderer_key]
                    ),
                ),
                ("renderer_version", models.PositiveSmallIntegerField(default=1)),
                ("content_schema_version", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("category", models.CharField(db_index=True, max_length=80)),
                ("sort_order", models.PositiveSmallIntegerField(db_index=True, default=0)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                (
                    "cover_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="theme_covers",
                        to="media_library.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "slug"],
            },
        ),
        migrations.CreateModel(
            name="ThemeMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("cover", "Cover"),
                            ("gallery", "Gallery"),
                            ("social", "Social"),
                            ("poster", "Poster"),
                        ],
                        max_length=16,
                    ),
                ),
                ("focal_x", models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ("focal_y", models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("alt_text", models.JSONField(default=dict)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="theme_usages",
                        to="media_library.mediaasset",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="catalog.theme",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThemeTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locale", models.CharField(choices=[("en", "EN"), ("id", "ID")], max_length=2)),
                ("name", models.CharField(max_length=120)),
                ("tagline", models.CharField(max_length=180)),
                ("description", models.TextField()),
                ("feature_copy", models.JSONField(blank=True, default=list)),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.theme",
                    ),
                ),
            ],
            options={
                "ordering": ["locale"],
            },
        ),
        migrations.CreateModel(
            name="PackageFeature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("feature_key", models.SlugField(max_length=80)),
                ("is_included", models.BooleanField(default=True)),
                ("value", models.CharField(blank=True, max_length=120)),
                ("labels", models.JSONField(default=dict)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="catalog.package",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "feature_key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("package", "feature_key"), name="unique_package_feature_key"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PackageTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locale", models.CharField(choices=[("en", "EN"), ("id", "ID")], max_length=2)),
                ("name", models.CharField(max_length=100)),
                ("summary", models.TextField()),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.package",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("package", "locale"), name="unique_package_translation_locale"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="theme",
            index=models.Index(
                fields=["status", "is_featured", "sort_order"], name="catalog_the_status_6253fb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="theme",
            constraint=models.UniqueConstraint(
                fields=("renderer_key", "renderer_version"), name="unique_theme_renderer_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="thememedia",
            constraint=models.UniqueConstraint(
                fields=("theme", "asset", "role"), name="unique_theme_asset_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="themetranslation",
            constraint=models.UniqueConstraint(
                fields=("theme", "locale"), name="unique_theme_translation_locale"
            ),
        ),
    ]
