# Generated by Django 5.2.15 on 2026-06-20 17:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WhatsAppIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("theme_slug", models.SlugField(blank=True, max_length=80)),
                ("package_code", models.SlugField(blank=True, max_length=40)),
                (
                    "locale",
                    models.CharField(
                        choices=[("id", "Bahasa Indonesia"), ("en", "English")],
                        default="id",
                        max_length=2,
                    ),
                ),
                ("campaign", models.CharField(blank=True, max_length=120)),
                ("source", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at", "theme_slug", "package_code"],
                        name="leads_whats_created_24e3cf_idx",
                    )
                ],
            },
        ),
    ]
