# Generated by Django 5.2.15 on 2026-06-20 17:22

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("media_library", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("public_slug", models.SlugField(max_length=100, unique=True)),
                (
                    "renderer_key",
                    models.CharField(
                        max_length=80, validators=[common.validators.validate_renderer_key]
                    ),
                ),
                ("renderer_version", models.PositiveSmallIntegerField(default=1)),
                ("content_schema_version", models.PositiveSmallIntegerField(default=1)),
                (
                    "default_locale",
                    models.CharField(
                        choices=[("id", "Bahasa Indonesia"), ("en", "English")],
                        default="id",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Review"),
                            ("published", "Published"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("is_sample", models.BooleanField(db_index=True, default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content",
                    models.JSONField(
                        default=dict, validators=[common.validators.validate_invitation_content]
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations",
                        to="catalog.package",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invitations",
                        to="catalog.theme",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("access_token_hash", models.CharField(max_length=128, unique=True)),
                ("display_name", models.CharField(max_length=120)),
                ("party_size", models.PositiveSmallIntegerField(default=1)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="invitations.invitation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvitationMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(max_length=40)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("alt_text", models.JSONField(default=dict)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invitation_usages",
                        to="media_library.mediaasset",
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="invitations.invitation",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvitationRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision_number", models.PositiveIntegerField()),
                (
                    "content",
                    models.JSONField(validators=[common.validators.validate_invitation_content]),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitation_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="invitations.invitation",
                    ),
                ),
            ],
            options={
                "ordering": ["-revision_number"],
            },
        ),
        migrations.CreateModel(
            name="WeddingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ceremony", "Ceremony"),
                            ("reception", "Reception"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("timezone", models.CharField(default="Asia/Jakarta", max_length=64)),
                ("venue_name", models.CharField(max_length=180)),
                ("address", models.TextField()),
                ("map_url", models.URLField(blank=True, max_length=500)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="invitations.invitation",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "starts_at"],
            },
        ),
        migrations.CreateModel(
            name="EventLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("province", models.CharField(max_length=100)),
                ("regency", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("village", models.CharField(max_length=100)),
                ("bmkg_adm4", models.CharField(blank=True, db_index=True, max_length=20)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to="invitations.weddingevent",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["status", "published_at"], name="invitations_status_536c82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["public_slug", "status"], name="invitations_public__76601f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invitationmedia",
            constraint=models.UniqueConstraint(
                fields=("invitation", "asset", "role"), name="unique_invitation_asset_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="invitationrevision",
            constraint=models.UniqueConstraint(
                fields=("invitation", "revision_number"), name="unique_invitation_revision_number"
            ),
        ),
    ]
