from django.urls import path

from invitations.views import (
    InvitationDetailView,
    InvitationRSVPView,
    InvitationWeatherView,
    PublicGuestRSVPCreateView,
    StaffGuestAnonymizeView,
    StaffGuestArchiveView,
    StaffInvitationGuestListCreateView,
    StaffInvitationMusicView,
    StaffInvitationOperationListView,
    StaffInvitationPublishView,
)

urlpatterns = [
    path(
        "invitations/<slug:public_slug>",
        InvitationDetailView.as_view(),
        name="invitation-detail",
    ),
    path(
        "invitations/<slug:public_slug>/weather",
        InvitationWeatherView.as_view(),
        name="invitation-weather",
    ),
    path(
        "invitations/<slug:public_slug>/rsvp",
        InvitationRSVPView.as_view(),
        name="invitation-rsvp",
    ),
    path(
        "invitations/<slug:public_slug>/public-rsvp",
        PublicGuestRSVPCreateView.as_view(),
        name="invitation-public-rsvp-create",
    ),
    path(
        "admin/invitations",
        StaffInvitationOperationListView.as_view(),
        name="admin-invitation-list",
    ),
    path(
        "admin/invitations/<slug:public_slug>/publish",
        StaffInvitationPublishView.as_view(),
        name="admin-invitation-publish",
    ),
    path(
        "admin/invitations/<slug:public_slug>/guests",
        StaffInvitationGuestListCreateView.as_view(),
        name="admin-invitation-guest-list",
    ),
    path(
        "admin/invitations/<slug:public_slug>/music",
        StaffInvitationMusicView.as_view(),
        name="admin-invitation-music",
    ),
    path(
        "admin/guests/<uuid:guest_id>/archive",
        StaffGuestArchiveView.as_view(),
        name="admin-guest-archive",
    ),
    path(
        "admin/guests/<uuid:guest_id>/anonymize",
        StaffGuestAnonymizeView.as_view(),
        name="admin-guest-anonymize",
    ),
]
