from django.urls import path

from invitations.views import (
    ClientGuestExportView,
    ClientInvitationApprovePublishView,
    ClientInvitationDetailView,
    ClientInvitationGuestListView,
    ClientInvitationListView,
    ClientInvitationMusicView,
    ClientInvitationSubmitRevisionView,
    InvitationDetailView,
    InvitationRSVPView,
    InvitationWeatherView,
    StaffGuestAnonymizeView,
    StaffGuestArchiveView,
    StaffInvitationGuestListCreateView,
    StaffInvitationMusicView,
    StaffInvitationOperationListView,
    StaffInvitationPublishView,
)

urlpatterns = [
    path(
        "invitations/<slug:public_slug>",
        InvitationDetailView.as_view(),
        name="invitation-detail",
    ),
    path(
        "invitations/<slug:public_slug>/weather",
        InvitationWeatherView.as_view(),
        name="invitation-weather",
    ),
    path(
        "invitations/<slug:public_slug>/rsvp",
        InvitationRSVPView.as_view(),
        name="invitation-rsvp",
    ),
    path("client/invitations", ClientInvitationListView.as_view(), name="client-invitation-list"),
    path(
        "client/invitations/<slug:public_slug>",
        ClientInvitationDetailView.as_view(),
        name="client-invitation-detail",
    ),
    path(
        "client/invitations/<slug:public_slug>/submit-revision",
        ClientInvitationSubmitRevisionView.as_view(),
        name="client-invitation-submit-revision",
    ),
    path(
        "client/invitations/<slug:public_slug>/approve-publish",
        ClientInvitationApprovePublishView.as_view(),
        name="client-invitation-approve-publish",
    ),
    path(
        "client/invitations/<slug:public_slug>/guests/export",
        ClientGuestExportView.as_view(),
        name="client-guest-export",
    ),
    path(
        "client/invitations/<slug:public_slug>/guests",
        ClientInvitationGuestListView.as_view(),
        name="client-guest-list",
    ),
    path(
        "client/invitations/<slug:public_slug>/music",
        ClientInvitationMusicView.as_view(),
        name="client-invitation-music",
    ),
    path(
        "admin/invitations",
        StaffInvitationOperationListView.as_view(),
        name="admin-invitation-list",
    ),
    path(
        "admin/invitations/<slug:public_slug>/publish",
        StaffInvitationPublishView.as_view(),
        name="admin-invitation-publish",
    ),
    path(
        "admin/invitations/<slug:public_slug>/guests",
        StaffInvitationGuestListCreateView.as_view(),
        name="admin-invitation-guest-list",
    ),
    path(
        "admin/invitations/<slug:public_slug>/music",
        StaffInvitationMusicView.as_view(),
        name="admin-invitation-music",
    ),
    path(
        "admin/guests/<uuid:guest_id>/archive",
        StaffGuestArchiveView.as_view(),
        name="admin-guest-archive",
    ),
    path(
        "admin/guests/<uuid:guest_id>/anonymize",
        StaffGuestAnonymizeView.as_view(),
        name="admin-guest-anonymize",
    ),
]
