from django.urls import path

from invitations.views import (
    InvitationDetailView,
    InvitationPreviewDetailView,
    InvitationRSVPView,
    InvitationWeatherView,
    PublicGuestRSVPCreateView,
    StaffGuestAnonymizeView,
    StaffGuestArchiveView,
    StaffInvitationGuestLinkExportView,
    StaffInvitationGuestLinkImportTemplateView,
    StaffInvitationGuestLinkImportView,
    StaffInvitationGuestLinkListCreateView,
    StaffInvitationGuestListCreateView,
    StaffInvitationMusicView,
    StaffInvitationOperationListView,
    StaffInvitationPublishView,
)

urlpatterns = [
    path(
        "invitations/<slug:public_slug>",
        InvitationDetailView.as_view(),
        name="invitation-detail",
    ),
    path(
        "invitations/<slug:public_slug>/preview",
        InvitationPreviewDetailView.as_view(),
        name="invitation-preview-detail",
    ),
    path(
        "invitations/<slug:public_slug>/weather",
        InvitationWeatherView.as_view(),
        name="invitation-weather",
    ),
    path(
        "invitations/<slug:public_slug>/rsvp",
        InvitationRSVPView.as_view(),
        name="invitation-rsvp",
    ),
    path(
        "invitations/<slug:public_slug>/public-rsvp",
        PublicGuestRSVPCreateView.as_view(),
        name="invitation-public-rsvp-create",
    ),
    path(
        "admin/invitations",
        StaffInvitationOperationListView.as_view(),
        name="admin-invitation-list",
    ),
    path(
        "admin/invitations/<slug:public_slug>/publish",
        StaffInvitationPublishView.as_view(),
        name="admin-invitation-publish",
    ),
    path(
        "admin/invitations/<slug:public_slug>/guests",
        StaffInvitationGuestListCreateView.as_view(),
        name="admin-invitation-guest-list",
    ),
    path(
        "admin/invitations/<slug:public_slug>/guest-links",
        StaffInvitationGuestLinkListCreateView.as_view(),
        name="admin-invitation-guest-link-list",
    ),
    path(
        "admin/invitations/<slug:public_slug>/guest-links/export",
        StaffInvitationGuestLinkExportView.as_view(),
        name="admin-invitation-guest-link-export",
    ),
    path(
        "admin/invitations/<slug:public_slug>/guest-links/import-template",
        StaffInvitationGuestLinkImportTemplateView.as_view(),
        name="admin-invitation-guest-link-import-template",
    ),
    path(
        "admin/invitations/<slug:public_slug>/guest-links/import",
        StaffInvitationGuestLinkImportView.as_view(),
        name="admin-invitation-guest-link-import",
    ),
    path(
        "admin/invitations/<slug:public_slug>/music",
        StaffInvitationMusicView.as_view(),
        name="admin-invitation-music",
    ),
    path(
        "admin/guests/<uuid:guest_id>/archive",
        StaffGuestArchiveView.as_view(),
        name="admin-guest-archive",
    ),
    path(
        "admin/guests/<uuid:guest_id>/anonymize",
        StaffGuestAnonymizeView.as_view(),
        name="admin-guest-anonymize",
    ),
]
